Algoritmo "Entrada e Saida de dados"
// Descrição   : Entrada e Saida de dados
// Autor(a)    : Thaís Rodrigues
// Data atual  : 12/05/2021
Var
// Seção de Declarações das variáveis 
    nome: caractere
    nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome:")
   leia(nome)
   escreval("Digite a sua nota:")
   leia(nota)
   
   escreval("O nome digitado foi: ", nome)
   escreval("A nota digitada foi: ", nota)

Fimalgoritmo